# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'ImageCropper' do
    pod 'React', '../node_modules/React'
    pod 'RSKImageCropper', '~> 1.5.1'
end

